[project]
name = "qrcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.13.0.92",
    "pyzbar>=0.1.9",
]

[dependency-groups]
dev = [
    "qrcode[pil]",
]

[tool.uv.sources]
qrcode = { workspace = true }
